services:
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: python_task
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - python_task
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
    networks:
      - python_task
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
    external: true

networks:
  python_task:
    external: true
